spring:
  datasource:
    url: jdbc:mysql://dockerce01:3306/demo
    username: root
    password: password
    
    platform: mysql
    initialization-mode: always
    
logging:
  level:
    org.springframework.data: debug
    org.springframework.jdbc: debug